### ISSUE TITLE
Protontricks and Linux doesn't appear to work

### ISSUE THREAD

**Issue by Fairweather-Furry** [PKBeam/Edda#101]
I'm attempting to run Edda under Linux (Currently using Linux Mint 21.3). Attempting to run Edda under Proton either as a direct Steam game, or by attempting the Protontricks program mentioned here #18 results in nothing being launched. Steam games under Proton works, so this is not a proton issue. I have attempted with the version bundled with .net, and I have also attempted adding a windows .net to a wine prefix for Edda as well, which also has not worked. Edda 1.2.3.

**Comment by PKBeam** [comment]
> Steam games under Proton works, so this is not a proton issue.

This isn’t true in general. Proton isn’t perfect; it’s remarkably compatible with many games, but there are just as many that have issues or don’t run at all.

1.2.3 launches fine on Windows, so that means something’s going wrong with how Proton tries to run Edda.

One of the changes introduced after 1.1.0 is probably to blame. Maybe the update to .NET 7.0 or the spectrogram libraries?

Either way, we likely won’t be providing official support for Edda on any OS that isn’t Windows, since we can’t control how other devs work on their VMs/compatibility layers. The advice you linked before is just a suggestion.

**Comment by Brollyy** [comment]
I recently switched from Windows to Ubuntu 24, and out of curiosity tried to see if I'd be able to run Edda. I was able to configure wine to start up Edda-v1.2.7-NoRuntime after installing .NET Runtime separately. It's very laggy, spectrogram doesn't render correctly and there's a few more quirks, but in theory it works 😅
