### ISSUE TITLE
Track unsaved changes to a map

### ISSUE THREAD

**Issue by PKBeam** [PKBeam/Edda#26]
Right now the user will unconditionally be prompted to save when they try to close the program.

We should track any unsaved changes to the map and only prompt to save if there are any changes pending.

**Comment by Brollyy** [comment]
I'll work on that.

**Comment by Brollyy** [comment]
To be clear, what do you mean here by "track any unsaved changes"?
The way I see this, we have several options to implement this:

1. mark the editor as "dirty" whenever user performs any action that needs to be saved - this is the easiest to implement and maintain, but doesn't allow very granular control in some cases (explained below);
2. keep a list of unsaved actions performed by the user, similar to the EditHistory on the Notes - this is more flexible than the easiest option, and I imagine with auto-save it wouldn't impact memory usage that much, but it'll be harder to implement;
3. on closing, check if there are any changes between in-memory RagnarockMap and the file - this would impact performance the most, but would be a surefire way to know whether the file has any changes.

The cases I'm concerned with are operations on note history, e.g. placing a note and then undoing it with Ctrl+Z - 1st option will mark the file as "dirty", but user might be expecting that no changes have been done; 2nd option could cover this by defining which changes "cancel" themselves when next to each other.

Overall, I'd still go with 1st option due to simplicity and safety - I don't imagine getting it exactly right in all edge cases matters that much and if we must get it wrong, it's better to have it ask if you need to save again, especially since user had to do the action themselves to trigger this.

**Comment by Brollyy** [comment]
Released in 1.2.0
