### ISSUE TITLE
ffmpeg-temp.exe should not be deleted once created, instead it should be overwritten or left alone

### ISSUE THREAD

**Issue by UnforeseenOcean** [PKBeam/Edda#48]
This is a minor issue, however, it may cause confusion. When creating a preview, currently the program drops `ffmpeg-temp.exe` in the folder it uses to hold temporary files, then attempts to delete it. When it fails because the program didn't quit on time or something is using the program, it displays an error message. To prevent this, the dropped executable file should not be deleted, instead, it should be overwritten (condition: when file hash does not match) or simply left where it is. While this may be considered a bad practice, it reduces the chances of something going wrong in the future. To prevent possible filename collision with other programs, it might be a good idea to further rename the file to `ffmpeg-temp-edda.exe` or similar.

**Comment by Brollyy** [comment]
I really dislike the idea of not cleaning up temporary files when we're done with them.

The only process using that temporary file should be the one that generates the preview, so the issue seems to be on Edda for not managing it correctly - [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=net-7.0) suggests that finished processes still need to be closed to free up all of the resources allocated, so I'll look into that.

The error popup really should not be displayed to the user if a temporary file was not deleted correctly, especially since the preview file was likely still generated correctly - logging the error seems more appropriate and then retrying the delete when Edda is closed, while error popup should be reserved for when the FFMPEG process itself fails to generate the preview.
