### ISSUE TITLE
Corrupted OGG file error on valid OGG file

### ISSUE THREAD

**Issue by Crimson-foxGITHUB** [PKBeam/Edda#9]
I found that Edda can sometimes report "invalid OGG file" with files that play back just fine in foobar2000, for some reason. In the comment below is said OGG file in a .zip:

**Comment by Crimson-foxGITHUB** [comment]
[WE ARE JAPANESE GOBLIN.zip](https://github.com/PKBeam/Edda/files/8597997/WE.ARE.JAPANESE.GOBLIN.zip)

**Comment by PKBeam** [comment]
This is detailed on the website:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/18737124/166131180-475f8cd3-f872-4455-a89c-16a7db9c2c07.png">

FFprobe shows that this .ogg file uses the Opus codec.
```
> ffprobe.exe '.\WE ARE JAPANESE GOBLIN.ogg'

...

Input #0, ogg, from '.\WE ARE JAPANESE GOBLIN.ogg':
  Duration: 00:04:03.05, start: 0.007500, bitrate: 125 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavf57.19.100
```

I also doubt Ragnarock itself has support for Opus files. This is very much an edge case since almost all .ogg files are Vorbis; .opus is the recommended file extension for Opus files.
